version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre-build:
    commands:
      - curl -o- -L https://yarnpkg.com/install.sh | bash
  build:
    commands:
      - yarn
  post_build:
    commands:
      - echo Build completed on `date`
  artifacts:
    files:
      - apps/**/*
      - node_modules/**/*
      - dist/**/*
      - package.json

