import { IListType } from '@myworkspace/shared-types';

export const useCollegeList: Array<IListType> = [
  {
    nameInArabic: 'افيكا – الكلية الأكاديمية للهندسة في تل ابيب',
    nameInHebrew: 'אפקה - המכללה האקדמית להנדסה בתל-אביב',
    websiteUrl: 'https://www.afeka.ac.il/',
    imageUrl: 'Afeka.png',
  },
  {
    nameInArabic: 'بتسلئيل  - المعهد العالي لحرف الفنون بالقدس',
    nameInHebrew: 'בצלאל -אקדמיה לאומנות ועיצוב ירושלים',
    websiteUrl: 'http://www.bezalel.ac.il/',
    imageUrl: 'Batslal.png',
  },
  {
    nameInArabic: 'الأكاديمية للموسيقى والرقص في القدس',
    nameInHebrew: 'האקדמיה למוסיקה ולמחול בירושלים ',
    websiteUrl: 'https://www.jamd.ac.il/',
    imageUrl: 'MusecCollage.jpg',
  },
  {
    nameInArabic: 'الكلية الأكاديمية احفا',
    nameInHebrew: 'המכללה האקדמית אחוה ',
    websiteUrl: 'https://www.achva.ac.il/',
    imageUrl: 'AhvaCollage.png',
  },
  {
    nameInArabic: 'الكلية الأكاديمية اشكلون',
    nameInHebrew: 'המכללה האקדמית אשקלון',
    websiteUrl: 'https://www.aac.ac.il/',
    imageUrl: 'Ashklon.jpg',
  },
  {
    nameInArabic: 'الكلية الأكاديمية الجليل الغربي',
    nameInHebrew: 'המכללה האקדמית גליל מערבי',
    websiteUrl: 'https://www.wgalil.ac.il/',
    imageUrl: 'GalelMarbe.png',
  },
  {
    nameInArabic: 'الكلية الأكاديمية هداسا, القدس',
    nameInHebrew: 'המכללה האקדמית הדסה, ירושלים ',
    websiteUrl: 'https://www.hac.ac.il/',
    imageUrl: 'Hadasa.png',
  },
  {
    nameInArabic: 'الكلية الأكاديمية كينرت غور الأردن',
    nameInHebrew: 'המכללה האקדמית עמק הירדן',
    websiteUrl: 'https://www.kinneret.ac.il/Web/Default.aspx',
    imageUrl: 'KanertCollage.jpg',
  },
  {
    nameInArabic: 'الكلية الأكاديمية للهندسة سامي شمعون',
    nameInHebrew: 'המכללה האקדמית להנדסה סמי שמעון',
    websiteUrl: 'https://www.sce.ac.il/',
    imageUrl: 'SameShemon.png',
  },
  {
    nameInArabic: 'الكلية الأكاديمية سبير ',
    nameInHebrew: 'המכללה האקדמית ספיר ',
    websiteUrl: 'https://www.sapir.ac.il/',
    imageUrl: 'Sapher.png',
  },
  {
    nameInArabic: 'الكلية الأكاديمية عيميك يزرعيل ',
    nameInHebrew: 'המכללה האקדמית עמק יזרעאל',
    websiteUrl: 'https://www.yvc.ac.il/',
    imageUrl: 'EmkYsrael.jpg',
  },
  {
    nameInArabic: 'الكلية الأكاديمية صفد ',
    nameInHebrew: 'המכללה האקדמית צפת ',
    websiteUrl: 'https://www.zefat.ac.il/',
    imageUrl: 'tsfat.png',
  },
  {
    nameInArabic: 'الكلية الأكاديمية تل ابيب يافا',
    nameInHebrew: 'המכללה האקדמית תל אביב -יפו ',
    websiteUrl: 'https://www.mta.ac.il/he-il/',
    imageUrl: 'TelAvevCollage.png',
  },
  {
    nameInArabic: 'الكلية الاكاديمية تل حاي',
    nameInHebrew: 'המכללה האקדמית תל חי ',
    websiteUrl: 'https://www.telhai.ac.il/',
    imageUrl: 'TalHay.png',
  },
  {
    nameInArabic: 'مركز روبين الأكاديمي',
    nameInHebrew: 'המרכז האקדמי רופין',
    websiteUrl: 'https://www.ruppin.ac.il/Pages/hp.aspx',
    imageUrl: 'Ropen.jpg',
  },
  {
    nameInArabic: 'المركز التكنولوجي حولون',
    nameInHebrew: 'מכון טכנולוגי חולון ',
    websiteUrl: 'https://www.hit.ac.il/',
    imageUrl: 'HolonTech.jpg',
  },
  {
    nameInArabic: 'الكلية الأكاديمية للهندسة اورط براوده',
    nameInHebrew: 'מכללה האקדמית להנדסה אורט בראודה',
    websiteUrl: 'http://www.braude.ac.il/',
    imageUrl: 'OrtProwda.png',
  },
  {
    nameInArabic: 'عزرائيلي الكلية الأكاديمية للهندسة في القدس',
    nameInHebrew: 'עזריאלי המכללה האקדמית להנדסה בירושלים',
    websiteUrl: 'https://www.jce.ac.il/',
    imageUrl: 'Israely.png',
  },
  {
    nameInArabic: 'الكلية الأكاديمية شنكار',
    nameInHebrew: 'שנקר הנדסה עיצוב אמנות',
    websiteUrl: 'https://www.shenkar.ac.il/he',
    imageUrl: 'Shanker.png',
  },
  {
    nameInArabic: 'الكلية الأكاديمية للمجتمع والفنون',
    nameInHebrew: 'המכללה האקדמית לחברה ואומנויות ',
    websiteUrl: ' https://www.asa.ac.il/',
    imageUrl: 'Omnot.jpg',
  },
  {
    nameInArabic: 'الكلية الأكاديمية لإسرائيل رمات غان',
    nameInHebrew: 'המכללה האקדמית לישראל ברמת גן',
    websiteUrl: 'https://www.iac.ac.il/',
    imageUrl: 'RamatGan.png',
  },
  {
    nameInArabic: 'الكلية الأكاديمية نتانيا',
    nameInHebrew: 'המכללה האקדמית נתניה ',
    websiteUrl: 'https://www.netanya.ac.il/Pages/default.aspx',
    imageUrl: 'Natanya.png',
  },
  {
    nameInArabic: 'المسار الاكاديمي لكلية الإدارة',
    nameInHebrew: 'המסלול האקדמי של המכללה למנהל',
    websiteUrl: 'https://www.colman.ac.il/',
    imageUrl: 'MangerCollage.png',
  },
  {
    nameInArabic: 'المركز الأكاديمي للحقوق والإدارة ',
    nameInHebrew: 'המרכז האקדמי למשפט ולעסקים',
    websiteUrl: '',
    imageUrl: 'BussnesCollage.png',
  },
  {
    nameInArabic: 'المركز الاكاديمي بيريس',
    nameInHebrew: 'המרכז האקדמי פרס',
    websiteUrl: 'https://www.pac.ac.il/',
    imageUrl: 'prasCollage.jpg',
  },
  {
    nameInArabic: 'المركز الأكاديمي أبواب العلم والحقوق',
    nameInHebrew: 'המרכז האקדמי שערי מדע ומשפט',
    websiteUrl: 'https://mishpat.ac.il/',
    imageUrl: 'ShareMada.png',
  },
  {
    nameInArabic: 'المركز المتعدد المجالات هرتسليا',
    nameInHebrew: 'המרכז הבינתחומי הרצליה',
    websiteUrl: 'https://www.idc.ac.il/he/pages/home.aspx',
    imageUrl: 'HertzlyaCollage.png',
  },
  {
    nameInArabic: 'المركز الأكاديمي اور يهودا',
    nameInHebrew: 'המרכז האקדמי אור יהודה',
    websiteUrl: 'https://www.mla.ac.il/',
    imageUrl: 'OrYahoda.png',
  },
  {
    nameInArabic: 'الكلية الأكاديمية اونو ',
    nameInHebrew: 'הקריה האקדמית אונו ',
    websiteUrl: 'https://www.ono.ac.il/',
    imageUrl: 'OneCollage.png',
  },
  {
    nameInArabic: 'القاسمي كليه أكاديمية للتربية والتعليم',
    nameInHebrew: 'אלקאסמי -מכללה אקדמית לחינוך',
    websiteUrl: 'https://www.qsm.ac.il/he/?mod:articles&ID:468',
    imageUrl: 'Alkaseme.png',
  },

  {
    nameInArabic: 'الكلية الأكاديمية بيت يبرل',
    nameInHebrew: 'המכללה האקדמית בית-ברל ',
    websiteUrl: 'https://www.beitberl.ac.il/',
    imageUrl: 'BetBerll.jpg',
  },
  {
    nameInArabic: 'الكلية الأكاديمية العربية للتربية في إسرائيل - حيفا',
    nameInHebrew: 'המכללה האקדמית הערבית לחינוך בישראל -חיפה',
    websiteUrl: 'http://www.arabcol.ac.il/',
    imageUrl: 'ArabicCollage.jpg',
  },
  {
    nameInArabic: 'الكلية الأكاديمية فنجيت',
    nameInHebrew: 'המכללה האקדמית וינגייט',
    websiteUrl: 'https://www.wincol.ac.il/',
    imageUrl: 'Venged.png',
  },
  {
    nameInArabic: 'الكلية الأكاديمية التربية والرياضة اوهلو كتسرين ',
    nameInHebrew: 'המכללה האקדמית לחינוך ולספורט אוהלו בקצרין ',
    websiteUrl: 'http://www.ohalo.ac.il/',
    imageUrl: 'OhloCollage.jpg',
  },
  {
    nameInArabic: 'الكلية الأكاديمية للتربية على اسم دافيد يلين ',
    nameInHebrew: 'המכללה האקדמית לחינוך דוד ילין',
    websiteUrl: 'https://www.dyellin.ac.il/',
    imageUrl: 'DodYalen.png',
  },
  {
    nameInArabic: 'الكلية الأكاديمية للتربية على اسم كي',
    nameInHebrew: 'המכללה האקדמית לחינוך קיי',
    websiteUrl: 'https://www.kaye.ac.il/',
    imageUrl: 'Key.png',
  },
  {
    nameInArabic: 'الكليه الاكاديميه للتربيه على اسم ا.د. جوردون',
    nameInHebrew: 'המכללה האקדמית לחינוך א.ד. גורדון',
    websiteUrl: 'https://www.gordon.ac.il/',
    imageUrl: 'Gorden.png',
  },
  {
    nameInArabic: 'المركز الأكاديمي للتصميم والتعليم فيتسو',
    nameInHebrew: 'המרכז האקדמי לעיצוב ולחינוך ויצו – נרי בלומפילד',
    websiteUrl: 'https://www.wizodzn.ac.il/',
    imageUrl: 'Vetsav.png',
  },

  {
    nameInArabic: 'الكلية الأكاديمية للتربية -اورانيم ',
    nameInHebrew: 'המכללה האקדמית לחינוך אורנים ',
    websiteUrl: 'http://www.oranim.ac.il/sites/heb/pages/default.aspx',
    imageUrl: 'Oranem.png',
  },

  {
    nameInArabic: 'كليه لفينسكي للتربية',
    nameInHebrew: 'מכללת לוינסקי לחינוך ',
    websiteUrl: 'https://www.levinsky.ac.il/',
    imageUrl: 'Lenske.png',
  },
  {
    nameInArabic: 'كليه سخنين الأكاديمية لأعداد وتأهيل المعلمين ',
    nameInHebrew: 'מכללת סכנין – מכללה אקדמית להכשרת עובדי הוראה ',
    websiteUrl: 'http://www.sakhnin.ac.il/',
    imageUrl: 'Skhnin.png',
  },
  {
    nameInArabic: 'كليه سمينار هكيبوتسيم للتربية -التكنولوجيا والفنون ',
    nameInHebrew: 'סמינר הקיבוצים – המכללה לחינוך לטכנולוגיה ולאומנויות',
    websiteUrl: 'https://www.smkb.ac.il/',
    imageUrl: 'SamenarHakebotsem.png',
  },
];
